on: [push, pull_request]
name: ci
jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Start PF Container
        env:
          PING_IDENTITY_DEVOPS_USER: ${{ secrets.PING_IDENTITY_DEVOPS_USER }}
          PING_IDENTITY_DEVOPS_KEY: ${{ secrets.PING_IDENTITY_DEVOPS_KEY }}
        run: |
          make pf-init

      - name: Test
        run: |
          go test -count=1 -v -timeout 30m  ./...
